# For DC the use_DC flag must be enabled!
ec_board_ctrl :
  eth_iface: rteth0
  sync_cycle_time_ns: 2000000 #this value is used also for DC sync. 
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 300000000
  sync_point_ns : 500000
  power_off_boards: false
  reset_micro : true
  use_DC: true
  
ec_boards_base :
  app_mode : run_mode
  # app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  #fault_power_off : true
  use_ecat_pos_as_id : false
  pb_utils_verbose : true

zmq_pub :
  base_port : 9000
  uri : "tcp://*:"
  fd_timeout_us : 100000

zmq_rep :
  uri: "tcp://*:5555"
  zmq_rcvtimeo_ms : 500
  #pipe_prefix : "/tmp/nrt_pipes/"
  pb_utils_verbose : true

ati_config :
  ati_ip_addr : 192.168.1.1
  ft_ecat_pos : 1
  save_calib_matrix : false
  calib_mat_file : ../examples/ati_ft6_calib/data/ones.txt
  #calib_mat_file : ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_right_Foot_ft_147_sens8.txt
  dump_log : true


#############################
## Synapticon driver config
#############################
SynapticonESC_X:
  #joint_config:
    ##robot_id: 1                     # Maximum 8 bit
    #module_type: 5                   # Maximum 4 bit (module_params)
    #module_size: 2                   # Maximum 4 bit (module_params)
    #module_id:   1                   # Maxum 8 bit   (module_params)
    #module_revision: 0                # Maximum 8 bit (module_params)
  #brake:
    #brake_voltage: 17               # Voltage (in Volt) that will be applied to the coil of the brake
  #motor_configuration:
    #inertia: 0.000017668 #kg*m^2
  #control_mode: 3B_motor_pos_ctrl   #esc.cpp --> controller_type_map
  #pid:                                                          # Gain value for the different type of controllers (be sure that this value have been tuned well! They will be used as the default at starting the drive, unless who start the drive (XBot) will override them)
    #position: [0.0062845, 0.0 , 0.0 , 6.578719 , 311.577179]    #3B_motor_pos_ctrl: 0: P_Pos, 1: I_Pos, 2: D_Pos, 3:P_Vel, 4:I_Vel
    #velocity: [10, 300 , 0.0 ]                                  #71_motor_speed_ctrl, 0: P, 1: I, 2: D
    #current: [2000, 2000]                                       #CC_current_ctrl: 0: Damping [mill, 1 --> 1000 mill], 1: Settling time [us]
    #torque: [0.08, 0.0015, 0.007]                                    # Torque control, Kp, Ki, Kd. LIMIT: [0.09, 0, 0.009]

# arms
SynapticonESC_11:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_12:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_13:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0

SynapticonESC_14:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_15:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_101:
  position_limits_rad:
    min: -0.1
    max: 1.25
  link_zero_incr: 0

SynapticonESC_21:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_22:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_23:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0

SynapticonESC_24:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_25:
  position_limits_rad:
    min: -2.7
    max: 2.7
  link_zero_incr: 0

SynapticonESC_102:
  position_limits_rad:
    min: -0.1
    max: 1.25
  link_zero_incr: 0


# dagana

SynapticonESC_101:
  position_limits_rad:
    min: -0.01
    max: 2.7
  link_zero_incr: 0

SynapticonESC_102:
  position_limits_rad:
    min: -0.01
    max: 2.7
  link_zero_incr: 0


# fl leg

SynapticonESC_31:
  position_limits_rad:
    min: -0.70
    max: 0.70
  link_zero_incr: 774418

SynapticonESC_32:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 771956

SynapticonESC_33:
  position_limits_rad:
    min: -3.20
    max: 3.20
  link_zero_incr: -16386 #53126 aksim2 (before belt)

SynapticonESC_34:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0




# fr leg

SynapticonESC_41:
  position_limits_rad:
    min: -0.70
    max: 0.70
  link_zero_incr: 375744

SynapticonESC_42:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 901880

SynapticonESC_43:
  position_limits_rad:
    min: -3.20
    max: 3.20
  link_zero_incr: 45 #998954 aksim2 (before belt)

SynapticonESC_44:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0




# rl leg

SynapticonESC_51:
  position_limits_rad:
    min: -0.70
    max: 0.70
  link_zero_incr: 902594

SynapticonESC_52:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 1035096

SynapticonESC_53:
  position_limits_rad:
    min: -3.20
    max: 3.20
  link_zero_incr: -16417  #181440 aksim2 (before belt)

SynapticonESC_54:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0




# rr leg

SynapticonESC_61:
  position_limits_rad:
    min: -0.70
    max: 0.70
  link_zero_incr: 511443

SynapticonESC_62:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 1033167

SynapticonESC_63:
  position_limits_rad:
    min: -3.20
    max: 3.20
  link_zero_incr: 43 #216272 aksim2 (before belt)

SynapticonESC_64:
  position_limits_rad:
    min: -3.0
    max: 3.0
  link_zero_incr: 0

