launcher:
  launcher_config: launcher_config.yaml

ecat:
  uri: 10.24.15.100:5555

cartesian:
  cmd_vel_topics:
    - /omnisteering/cmd_vel
    - /policy_deploy_node/commands/base_velocity
    - ZMQ
  zmq_pub_remote: tcp://10.24.13.102:5051
