context:
  session: kyon
  params:
    hw_type: ec_pos
  .defines:
    - &embedded embedded@10.24.15.100
    - &control kyon@10.24.15.102
    - &vision kyon@10.24.15.101

    - &docker-xeno  kyon-noble-ros2-xeno-exp-1
    - &docker-base  kyon-noble-ros2-dev-1
    - &docker-isaac  kyon-isaac-base
    
    - &camera-up-serialno 52061328
    - &camera-down-serialno 56033502


imu: 
  cmd: ros2 launch vectornav vectornav.launch.py
  machine: *control
  ready_check: timeout 5 ros2 topic echo /xbotcore/imu/imu_link --once
  docker: *docker-base

ecat:
  cmd: ecat_master
  machine: *embedded
  docker: *docker-xeno

xbot2:
  cmd: xbot2-core --hw {hw_type} --config /home/user/xbot2_ws/src/kyon_config/xbot2/kyon_basic_ros2.yaml
  machine: *embedded
  ready_check: timeout 5 ros2 topic echo /xbotcore/joint_states --once
  docker: *docker-xeno
  depends: [imu]
  variants:
    verbose:
      cmd: "{cmd} -V"
    ctrl:
      - ec_idle:
          params:
            hw_type: ec_idle
      - ec_pos:
          params:
            hw_type: ec_pos
      - dummy:
          params:
            hw_type: dummy

park:
  cmd: ros2 run kyon_cartesio parking.py -a park
  machine: *embedded
  docker: *docker-xeno

unpark:
  cmd: ros2 run kyon_cartesio parking.py -a unpark
  machine: *embedded
  docker: *docker-xeno

zed_up:
  cmd: ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedxm serial_number:=52061328 camera_name:=zed_up
  machine: *vision
  docker: zed_ros2_jazzy_container
  ready_check: timeout 5 ros2 topic echo /zed_up/zed_node/rgb/color/rect/image/compressed --once

zed_down:
  cmd: ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedxm serial_number:=56033502 camera_name:=zed_down
  machine: *vision
  docker: zed_ros2_jazzy_container
  ready_check: timeout 5 ros2 topic echo /zed_down/zed_node/rgb/color/rect/image/compressed --once

lidar:
  cmd: ros2 run hesai_ros_driver hesai_ros_driver_node --ros-args -p config_path:=/home/user/xbot2_ws/src/kyon_config/hesai/top_qt128_config.yaml
  machine: *control
  docker: *docker-base
  ready_check: timeout 5 ros2 topic echo /lidar_points --once

# record_bag:
#   cmd: ~/data/record_bag.bash
#   machine: *control
#   docker: *docker-dev
#   show_ui: false

loco_isaac:
  cmd: ros2 launch policy_deploy_toolkit run_example.launch.xml use_sim_time:=false
  machine: *control
  docker: *docker-base
  show_ui: true
  variants:
    distilled:
      cmd: "{cmd} distilled:=true"
    heightscan:
      cmd: "{cmd} heightscan:=true"


morning_routine:
  cmd: /home/user/xbot2_ws/src/kyon_config/scripts/robot_start_routine.bash
  machine: *control
  docker: *docker-base
  show_ui: true

# loco_mjx:
#   cmd: cd /home/user/kyon_mjx/src/kyon_mjx && bash scripts/run_eval.bash
#   machine: *control
#   docker: gg-docker-dev-1
#   show_ui: true

# loco_mjx_ferk:
#   cmd: cd /home/user/kyon_mjx/src/kyon_mjx && bash scripts/run_ferk_eval.bash
#   machine: *control
#   docker: gg-docker-dev-1
#   show_ui: true

# homing_ferk:
#   cmd: cd /home/user/kyon_mjx/src/kyon_mjx && bash scripts/ferk_homing.bash
#   machine: *control
#   docker: gg-docker-dev-1
#   show_ui: true

