FROM hhcmhub/xbot2-focal-dev:latest

# get kernel version
ARG USER_ID=1000
ARG KERNEL_VER=0
ARG USER_NAME=kyon-ros1

# env
ENV PYTHONUNBUFFERED=1

# additional dependencies
# RUN sudo sh -c 'echo "deb http://xbot.cloud/xbot2/ubuntu/$(lsb_release -sc) /" > /etc/apt/sources.list.d/xbot-latest.list' && \
#     wget -q -O - http://xbot.cloud/xbot2/ubuntu/KEY.gpg | sudo apt-key add -
RUN sudo apt remove -y xbot2_desktop_full && sudo apt autoremove -y 
RUN sudo apt update && sudo apt install -y \ 
	xbot2_desktop_full \
	ros-noetic-realsense2-description \
	ros-noetic-realsense2-camera \
	ros-noetic-theora-image-transport \
    ros-noetic-moveit


# remove default user
RUN sudo userdel -r user

# add kyon user
USER root
RUN useradd -u $USER_ID -ms /bin/bash $USER_NAME
RUN adduser $USER_NAME sudo
RUN adduser $USER_NAME dialout

RUN echo "$USER_NAME:user" | chpasswd

WORKDIR /home/$USER_NAME

# bashrc
COPY --chown=$USER_NAME scripts /home/$USER_NAME/scripts
RUN cp /etc/skel/.bashrc .
RUN bash -c "echo source /home/${USER_NAME}/scripts/env.bash >> /home/$USER_NAME/.bashrc"

# set ownership to user for the whole home folder
RUN chown -R $USER_NAME .

# switch to user
USER $USER_NAME
SHELL [ "/bin/bash", "-ic" ]

# configure forest to use https
ENV HHCM_FOREST_CLONE_DEFAULT_PROTO=https

# pip deps
RUN pip install scipy

# build required software (requires valid netrc for auth)
RUN --mount=type=secret,id=netrc,dst=/home/$USER_NAME/.netrc,uid=$USER_ID /bin/bash scripts/build-base.bash
