[Interface]
Address    = 10.0.0.2/24
PrivateKey = B7u+Y7wL/XeIx8fFQE1nRbJFxNA/6mkh2D9jGghFUyM=

[Peer]
PublicKey           = <contents of /etc/wireguard/server.pub on kyon-control>
Endpoint            = <kyon-control public IP>:51820
AllowedIPs          = 10.0.0.0/24, 10.24.15.0/24
PersistentKeepalive = 25