[Interface]
Address    = 10.0.0.2/24
PrivateKey = <contents of ~/pilot.key>

[Peer]
PublicKey           = +cDPjR4w6Zey00OkL6jb5QQNGiE2kKZleiO4yGUmj18=
Endpoint            = <kyon-control public IP>:51820
AllowedIPs          = 10.0.0.0/24, 10.24.15.0/24
PersistentKeepalive = 25