services:
  base:
    image: hhcmhub/kyon-cetc-noble-ros2-xeno-v5:master
    stdin_open: true
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    network_mode: host
    cap_add:
      - ALL
    restart: no
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/user/.ssh  # ssh
      - ./../..:/home/user/xbot2_ws/src/kyon_config:ro
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https

  dev:
    extends: base
    image: hhcmhub/kyon-cetc-noble-ros2-xeno-v${KERNEL_VER}
    restart: always
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /usr/lib/modules:/usr/lib/modules
      - ~/.cache/kyon-cetc-noble-ros2-dev:/home/kyon_ros2/data
    environment:
      - CUSTOM_PS=(dev)
  sim:
    extends: base 
    image: hhcmhub/kyon-cetc-noble-ros2-sim
    volumes:
      - ~/.cache/kyon-cetc-noble-ros2-sim:/home/kyon_ros2/data

  xbot2_gui_server:
    extends: base
    entrypoint: bash -ic "cd ~/xbot2_ws/src/kyon_config; git pull origin master; xbot2_gui_server gui/ros2/gui_server_config.yaml; bash"
    restart: always
    environment:
      - CUSTOM_PS=(xbot2_gui_server)
