services:
  base:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ROS_IP: ${ROS_IP}
    stdin_open: true
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    network_mode: host
    cap_add:
      - ALL
    restart: no
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/user/.ssh  # ssh
      - ../../:/home/user/xbot2_ws/src/kyon_config:ro
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https
      - ZENOH_CONFIG_OVERRIDE
      - CONFIG_PATH_DOCKER

  dev:
    extends: base
    restart: always
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /usr/lib/modules:/usr/lib/modules
      - ~/.cache/kyon-noble-ros2-dev:/home/user/data
    environment:
      - CUSTOM_PS=(dev)

  xbot2_gui_server:
    extends: base
    entrypoint: bash -ic "cd ~/xbot2_ws/src/kyon_config; xbot2_gui_server gui/gui_server_config.yaml -p 8082; bash"
    restart: always
    environment:
      - CUSTOM_PS=(xbot2_gui_server)

  zenoh_router:
    extends: base
    entrypoint: bash -c "echo $$ZENOH_CONFIG_OVERRIDE && source /opt/ros/jazzy/setup.bash && export RUST_LOG=zenoh=debug,zenoh_transport=debug,zenoh_link_tcp=debug && ros2 run rmw_zenoh_cpp rmw_zenohd"
    restart: always
    environment:
      - ZENOH_CONFIG_OVERRIDE=$ZENOH_CONFIG_OVERRIDE_ROUTER
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - CUSTOM_PS=(zenoh_router)
